/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MockERC20__factory } from "./MockERC20__factory";
export { SizeDickCoinFactory__factory } from "./SizeDickCoinFactory__factory";
export { SizeGifting__factory } from "./SizeGifting__factory";
export { SizeRewards__factory } from "./SizeRewards__factory";
export { SizeStaking__factory } from "./SizeStaking__factory";
