/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockERC20 } from "./MockERC20";
export type { SizeDickCoinFactory } from "./SizeDickCoinFactory";
export type { SizeGifting } from "./SizeGifting";
export type { SizeRewards } from "./SizeRewards";
export type { SizeStaking } from "./SizeStaking";
