/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SizeStakingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "GROWER_BOOST"
      | "GROWER_MIN"
      | "LOCK_PERIOD"
      | "MAX_PENALTY_BPS"
      | "SHLONG_BOOST"
      | "SHLONG_MIN"
      | "SHOWER_BOOST"
      | "SHOWER_MIN"
      | "WHALE_BOOST"
      | "WHALE_MIN"
      | "accRewardPerShare"
      | "acceptOwnership"
      | "bufferedRewards"
      | "claimRewards"
      | "depositRewards"
      | "emergencyWithdraw"
      | "getBoost"
      | "getEarlyWithdrawalPenalty"
      | "getStakeInfo"
      | "getTier"
      | "isDepositor"
      | "owner"
      | "pause"
      | "paused"
      | "pendingOwner"
      | "previewUnstake"
      | "renounceOwnership"
      | "setDepositor"
      | "sizeToken"
      | "stake"
      | "stakes"
      | "totalEffectiveStaked"
      | "totalPenaltiesCollected"
      | "totalStaked"
      | "transferOwnership"
      | "unpause"
      | "unstake"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DepositorUpdated"
      | "EmergencyWithdraw"
      | "OwnershipTransferStarted"
      | "OwnershipTransferred"
      | "Paused"
      | "PenaltyRedistributed"
      | "RewardsClaimed"
      | "RewardsDeposited"
      | "Staked"
      | "Unpaused"
      | "Unstaked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "GROWER_BOOST",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GROWER_MIN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LOCK_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_PENALTY_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SHLONG_BOOST",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SHLONG_MIN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SHOWER_BOOST",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SHOWER_MIN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WHALE_BOOST",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "WHALE_MIN", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "accRewardPerShare",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bufferedRewards",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimRewards",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositRewards",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBoost",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEarlyWithdrawalPenalty",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStakeInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isDepositor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "previewUnstake",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDepositor",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(functionFragment: "sizeToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "stake", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "stakes", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "totalEffectiveStaked",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalPenaltiesCollected",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalStaked",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "unstake",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "GROWER_BOOST",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "GROWER_MIN", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "LOCK_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_PENALTY_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SHLONG_BOOST",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "SHLONG_MIN", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "SHOWER_BOOST",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "SHOWER_MIN", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "WHALE_BOOST",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "WHALE_MIN", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "accRewardPerShare",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bufferedRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBoost", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEarlyWithdrawalPenalty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStakeInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTier", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isDepositor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "previewUnstake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDepositor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sizeToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stake", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stakes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalEffectiveStaked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalPenaltiesCollected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalStaked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unstake", data: BytesLike): Result;
}

export namespace DepositorUpdatedEvent {
  export type InputTuple = [depositor: AddressLike, status: boolean];
  export type OutputTuple = [depositor: string, status: boolean];
  export interface OutputObject {
    depositor: string;
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyWithdrawEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    penalty: BigNumberish
  ];
  export type OutputTuple = [user: string, amount: bigint, penalty: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
    penalty: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PenaltyRedistributedEvent {
  export type InputTuple = [user: AddressLike, penaltyAmount: BigNumberish];
  export type OutputTuple = [user: string, penaltyAmount: bigint];
  export interface OutputObject {
    user: string;
    penaltyAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardsClaimedEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardsDepositedEvent {
  export type InputTuple = [depositor: AddressLike, amount: BigNumberish];
  export type OutputTuple = [depositor: string, amount: bigint];
  export interface OutputObject {
    depositor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakedEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    newTier: BigNumberish
  ];
  export type OutputTuple = [user: string, amount: bigint, newTier: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
    newTier: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnstakedEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    penalty: BigNumberish,
    newTier: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    amount: bigint,
    penalty: bigint,
    newTier: bigint
  ];
  export interface OutputObject {
    user: string;
    amount: bigint;
    penalty: bigint;
    newTier: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SizeStaking extends BaseContract {
  connect(runner?: ContractRunner | null): SizeStaking;
  waitForDeployment(): Promise<this>;

  interface: SizeStakingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  GROWER_BOOST: TypedContractMethod<[], [bigint], "view">;

  GROWER_MIN: TypedContractMethod<[], [bigint], "view">;

  LOCK_PERIOD: TypedContractMethod<[], [bigint], "view">;

  MAX_PENALTY_BPS: TypedContractMethod<[], [bigint], "view">;

  SHLONG_BOOST: TypedContractMethod<[], [bigint], "view">;

  SHLONG_MIN: TypedContractMethod<[], [bigint], "view">;

  SHOWER_BOOST: TypedContractMethod<[], [bigint], "view">;

  SHOWER_MIN: TypedContractMethod<[], [bigint], "view">;

  WHALE_BOOST: TypedContractMethod<[], [bigint], "view">;

  WHALE_MIN: TypedContractMethod<[], [bigint], "view">;

  accRewardPerShare: TypedContractMethod<[], [bigint], "view">;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  bufferedRewards: TypedContractMethod<[], [bigint], "view">;

  claimRewards: TypedContractMethod<[], [void], "nonpayable">;

  depositRewards: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  emergencyWithdraw: TypedContractMethod<[], [void], "nonpayable">;

  getBoost: TypedContractMethod<[_user: AddressLike], [bigint], "view">;

  getEarlyWithdrawalPenalty: TypedContractMethod<
    [_user: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        penaltyBps: bigint;
        penaltyPct: bigint;
        daysStaked: bigint;
        daysRemaining: bigint;
      }
    ],
    "view"
  >;

  getStakeInfo: TypedContractMethod<
    [_user: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        stakedAmount: bigint;
        pendingRewards: bigint;
        tier: bigint;
        boost: bigint;
        effectiveStake: bigint;
      }
    ],
    "view"
  >;

  getTier: TypedContractMethod<[_user: AddressLike], [bigint], "view">;

  isDepositor: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  previewUnstake: TypedContractMethod<
    [_user: AddressLike, _amount: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        userReceives: bigint;
        penalty: bigint;
        penaltyBps: bigint;
      }
    ],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setDepositor: TypedContractMethod<
    [_depositor: AddressLike, _status: boolean],
    [void],
    "nonpayable"
  >;

  sizeToken: TypedContractMethod<[], [string], "view">;

  stake: TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;

  stakes: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        amount: bigint;
        rewardDebt: bigint;
        pendingRewards: bigint;
        firstStakedAt: bigint;
        lastStakedAt: bigint;
        lastClaimAt: bigint;
      }
    ],
    "view"
  >;

  totalEffectiveStaked: TypedContractMethod<[], [bigint], "view">;

  totalPenaltiesCollected: TypedContractMethod<[], [bigint], "view">;

  totalStaked: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  unstake: TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "GROWER_BOOST"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "GROWER_MIN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LOCK_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_PENALTY_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SHLONG_BOOST"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SHLONG_MIN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SHOWER_BOOST"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SHOWER_MIN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "WHALE_BOOST"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "WHALE_MIN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "accRewardPerShare"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "bufferedRewards"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimRewards"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "depositRewards"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getBoost"
  ): TypedContractMethod<[_user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEarlyWithdrawalPenalty"
  ): TypedContractMethod<
    [_user: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        penaltyBps: bigint;
        penaltyPct: bigint;
        daysStaked: bigint;
        daysRemaining: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getStakeInfo"
  ): TypedContractMethod<
    [_user: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        stakedAmount: bigint;
        pendingRewards: bigint;
        tier: bigint;
        boost: bigint;
        effectiveStake: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTier"
  ): TypedContractMethod<[_user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isDepositor"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pendingOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "previewUnstake"
  ): TypedContractMethod<
    [_user: AddressLike, _amount: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        userReceives: bigint;
        penalty: bigint;
        penaltyBps: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDepositor"
  ): TypedContractMethod<
    [_depositor: AddressLike, _status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sizeToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "stake"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stakes"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        amount: bigint;
        rewardDebt: bigint;
        pendingRewards: bigint;
        firstStakedAt: bigint;
        lastStakedAt: bigint;
        lastClaimAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "totalEffectiveStaked"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalPenaltiesCollected"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalStaked"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unstake"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "DepositorUpdated"
  ): TypedContractEvent<
    DepositorUpdatedEvent.InputTuple,
    DepositorUpdatedEvent.OutputTuple,
    DepositorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyWithdraw"
  ): TypedContractEvent<
    EmergencyWithdrawEvent.InputTuple,
    EmergencyWithdrawEvent.OutputTuple,
    EmergencyWithdrawEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferStarted"
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PenaltyRedistributed"
  ): TypedContractEvent<
    PenaltyRedistributedEvent.InputTuple,
    PenaltyRedistributedEvent.OutputTuple,
    PenaltyRedistributedEvent.OutputObject
  >;
  getEvent(
    key: "RewardsClaimed"
  ): TypedContractEvent<
    RewardsClaimedEvent.InputTuple,
    RewardsClaimedEvent.OutputTuple,
    RewardsClaimedEvent.OutputObject
  >;
  getEvent(
    key: "RewardsDeposited"
  ): TypedContractEvent<
    RewardsDepositedEvent.InputTuple,
    RewardsDepositedEvent.OutputTuple,
    RewardsDepositedEvent.OutputObject
  >;
  getEvent(
    key: "Staked"
  ): TypedContractEvent<
    StakedEvent.InputTuple,
    StakedEvent.OutputTuple,
    StakedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "Unstaked"
  ): TypedContractEvent<
    UnstakedEvent.InputTuple,
    UnstakedEvent.OutputTuple,
    UnstakedEvent.OutputObject
  >;

  filters: {
    "DepositorUpdated(address,bool)": TypedContractEvent<
      DepositorUpdatedEvent.InputTuple,
      DepositorUpdatedEvent.OutputTuple,
      DepositorUpdatedEvent.OutputObject
    >;
    DepositorUpdated: TypedContractEvent<
      DepositorUpdatedEvent.InputTuple,
      DepositorUpdatedEvent.OutputTuple,
      DepositorUpdatedEvent.OutputObject
    >;

    "EmergencyWithdraw(address,uint256,uint256)": TypedContractEvent<
      EmergencyWithdrawEvent.InputTuple,
      EmergencyWithdrawEvent.OutputTuple,
      EmergencyWithdrawEvent.OutputObject
    >;
    EmergencyWithdraw: TypedContractEvent<
      EmergencyWithdrawEvent.InputTuple,
      EmergencyWithdrawEvent.OutputTuple,
      EmergencyWithdrawEvent.OutputObject
    >;

    "OwnershipTransferStarted(address,address)": TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PenaltyRedistributed(address,uint256)": TypedContractEvent<
      PenaltyRedistributedEvent.InputTuple,
      PenaltyRedistributedEvent.OutputTuple,
      PenaltyRedistributedEvent.OutputObject
    >;
    PenaltyRedistributed: TypedContractEvent<
      PenaltyRedistributedEvent.InputTuple,
      PenaltyRedistributedEvent.OutputTuple,
      PenaltyRedistributedEvent.OutputObject
    >;

    "RewardsClaimed(address,uint256)": TypedContractEvent<
      RewardsClaimedEvent.InputTuple,
      RewardsClaimedEvent.OutputTuple,
      RewardsClaimedEvent.OutputObject
    >;
    RewardsClaimed: TypedContractEvent<
      RewardsClaimedEvent.InputTuple,
      RewardsClaimedEvent.OutputTuple,
      RewardsClaimedEvent.OutputObject
    >;

    "RewardsDeposited(address,uint256)": TypedContractEvent<
      RewardsDepositedEvent.InputTuple,
      RewardsDepositedEvent.OutputTuple,
      RewardsDepositedEvent.OutputObject
    >;
    RewardsDeposited: TypedContractEvent<
      RewardsDepositedEvent.InputTuple,
      RewardsDepositedEvent.OutputTuple,
      RewardsDepositedEvent.OutputObject
    >;

    "Staked(address,uint256,uint256)": TypedContractEvent<
      StakedEvent.InputTuple,
      StakedEvent.OutputTuple,
      StakedEvent.OutputObject
    >;
    Staked: TypedContractEvent<
      StakedEvent.InputTuple,
      StakedEvent.OutputTuple,
      StakedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "Unstaked(address,uint256,uint256,uint256)": TypedContractEvent<
      UnstakedEvent.InputTuple,
      UnstakedEvent.OutputTuple,
      UnstakedEvent.OutputObject
    >;
    Unstaked: TypedContractEvent<
      UnstakedEvent.InputTuple,
      UnstakedEvent.OutputTuple,
      UnstakedEvent.OutputObject
    >;
  };
}
