/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SizeGiftingInterface extends Interface {
  getFunction(
    nameOrSignature: "MAX_BATCH" | "batchGift" | "gift" | "sizeToken"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Gift" | "PostTip"): EventFragment;

  encodeFunctionData(functionFragment: "MAX_BATCH", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "batchGift",
    values: [AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "gift",
    values: [AddressLike, BigNumberish, BytesLike, string]
  ): string;
  encodeFunctionData(functionFragment: "sizeToken", values?: undefined): string;

  decodeFunctionResult(functionFragment: "MAX_BATCH", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "batchGift", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gift", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sizeToken", data: BytesLike): Result;
}

export namespace GiftEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    amount: BigNumberish,
    postId: BytesLike,
    message: string
  ];
  export type OutputTuple = [
    from: string,
    to: string,
    amount: bigint,
    postId: string,
    message: string
  ];
  export interface OutputObject {
    from: string;
    to: string;
    amount: bigint;
    postId: string;
    message: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PostTipEvent {
  export type InputTuple = [
    from: AddressLike,
    postAuthor: AddressLike,
    amount: BigNumberish,
    postId: BytesLike
  ];
  export type OutputTuple = [
    from: string,
    postAuthor: string,
    amount: bigint,
    postId: string
  ];
  export interface OutputObject {
    from: string;
    postAuthor: string;
    amount: bigint;
    postId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SizeGifting extends BaseContract {
  connect(runner?: ContractRunner | null): SizeGifting;
  waitForDeployment(): Promise<this>;

  interface: SizeGiftingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_BATCH: TypedContractMethod<[], [bigint], "view">;

  batchGift: TypedContractMethod<
    [_recipients: AddressLike[], _amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  gift: TypedContractMethod<
    [
      _to: AddressLike,
      _amount: BigNumberish,
      _postId: BytesLike,
      _message: string
    ],
    [void],
    "nonpayable"
  >;

  sizeToken: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_BATCH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "batchGift"
  ): TypedContractMethod<
    [_recipients: AddressLike[], _amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "gift"
  ): TypedContractMethod<
    [
      _to: AddressLike,
      _amount: BigNumberish,
      _postId: BytesLike,
      _message: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sizeToken"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "Gift"
  ): TypedContractEvent<
    GiftEvent.InputTuple,
    GiftEvent.OutputTuple,
    GiftEvent.OutputObject
  >;
  getEvent(
    key: "PostTip"
  ): TypedContractEvent<
    PostTipEvent.InputTuple,
    PostTipEvent.OutputTuple,
    PostTipEvent.OutputObject
  >;

  filters: {
    "Gift(address,address,uint256,bytes32,string)": TypedContractEvent<
      GiftEvent.InputTuple,
      GiftEvent.OutputTuple,
      GiftEvent.OutputObject
    >;
    Gift: TypedContractEvent<
      GiftEvent.InputTuple,
      GiftEvent.OutputTuple,
      GiftEvent.OutputObject
    >;

    "PostTip(address,address,uint256,bytes32)": TypedContractEvent<
      PostTipEvent.InputTuple,
      PostTipEvent.OutputTuple,
      PostTipEvent.OutputObject
    >;
    PostTip: TypedContractEvent<
      PostTipEvent.InputTuple,
      PostTipEvent.OutputTuple,
      PostTipEvent.OutputObject
    >;
  };
}
