/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SizeDickCoinFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CREATOR_BPS"
      | "GAS_BPS"
      | "MAX_DICKCOINS"
      | "PROTOCOL_BPS"
      | "TOTAL_BPS"
      | "acceptOwnership"
      | "allDickCoins"
      | "autoStakeThreshold"
      | "dickCoins"
      | "distributeFees"
      | "gasWallet"
      | "getDickCoinCount"
      | "getDickCoinInfo"
      | "isAutoStakeReady"
      | "owner"
      | "pendingOwner"
      | "pendingWithdrawals"
      | "protocolWallet"
      | "registerDickCoin"
      | "renounceOwnership"
      | "setAutoStakeThreshold"
      | "setGasWallet"
      | "setProtocolWallet"
      | "transferOwnership"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AutoStakeThresholdReached"
      | "CreatorPaid"
      | "DickCoinRegistered"
      | "FeesReceived"
      | "FeesSplit"
      | "GasWalletUpdated"
      | "OwnershipTransferStarted"
      | "OwnershipTransferred"
      | "ProtocolWalletUpdated"
      | "WithdrawalPending"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "CREATOR_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "GAS_BPS", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "MAX_DICKCOINS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROTOCOL_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "TOTAL_BPS", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allDickCoins",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "autoStakeThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "dickCoins",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "distributeFees",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "gasWallet", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getDickCoinCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDickCoinInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAutoStakeReady",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingWithdrawals",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerDickCoin",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAutoStakeThreshold",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setGasWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setProtocolWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "CREATOR_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "GAS_BPS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MAX_DICKCOINS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PROTOCOL_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "TOTAL_BPS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allDickCoins",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "autoStakeThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "dickCoins", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "distributeFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gasWallet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDickCoinCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDickCoinInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAutoStakeReady",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingWithdrawals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "protocolWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerDickCoin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAutoStakeThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGasWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProtocolWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace AutoStakeThresholdReachedEvent {
  export type InputTuple = [tokenAddress: AddressLike, totalFees: BigNumberish];
  export type OutputTuple = [tokenAddress: string, totalFees: bigint];
  export interface OutputObject {
    tokenAddress: string;
    totalFees: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CreatorPaidEvent {
  export type InputTuple = [creator: AddressLike, amount: BigNumberish];
  export type OutputTuple = [creator: string, amount: bigint];
  export interface OutputObject {
    creator: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DickCoinRegisteredEvent {
  export type InputTuple = [tokenAddress: AddressLike, creator: AddressLike];
  export type OutputTuple = [tokenAddress: string, creator: string];
  export interface OutputObject {
    tokenAddress: string;
    creator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeesReceivedEvent {
  export type InputTuple = [tokenAddress: AddressLike, amount: BigNumberish];
  export type OutputTuple = [tokenAddress: string, amount: bigint];
  export interface OutputObject {
    tokenAddress: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeesSplitEvent {
  export type InputTuple = [
    tokenAddress: AddressLike,
    creatorAmount: BigNumberish,
    protocolAmount: BigNumberish,
    gasAmount: BigNumberish
  ];
  export type OutputTuple = [
    tokenAddress: string,
    creatorAmount: bigint,
    protocolAmount: bigint,
    gasAmount: bigint
  ];
  export interface OutputObject {
    tokenAddress: string;
    creatorAmount: bigint;
    protocolAmount: bigint;
    gasAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GasWalletUpdatedEvent {
  export type InputTuple = [oldWallet: AddressLike, newWallet: AddressLike];
  export type OutputTuple = [oldWallet: string, newWallet: string];
  export interface OutputObject {
    oldWallet: string;
    newWallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProtocolWalletUpdatedEvent {
  export type InputTuple = [oldWallet: AddressLike, newWallet: AddressLike];
  export type OutputTuple = [oldWallet: string, newWallet: string];
  export interface OutputObject {
    oldWallet: string;
    newWallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalPendingEvent {
  export type InputTuple = [recipient: AddressLike, amount: BigNumberish];
  export type OutputTuple = [recipient: string, amount: bigint];
  export interface OutputObject {
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SizeDickCoinFactory extends BaseContract {
  connect(runner?: ContractRunner | null): SizeDickCoinFactory;
  waitForDeployment(): Promise<this>;

  interface: SizeDickCoinFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CREATOR_BPS: TypedContractMethod<[], [bigint], "view">;

  GAS_BPS: TypedContractMethod<[], [bigint], "view">;

  MAX_DICKCOINS: TypedContractMethod<[], [bigint], "view">;

  PROTOCOL_BPS: TypedContractMethod<[], [bigint], "view">;

  TOTAL_BPS: TypedContractMethod<[], [bigint], "view">;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  allDickCoins: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  autoStakeThreshold: TypedContractMethod<[], [bigint], "view">;

  dickCoins: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, bigint, bigint, boolean] & {
        creator: string;
        tokenAddress: string;
        totalFeesReceived: bigint;
        creatorPaid: bigint;
        stakingDeployed: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  distributeFees: TypedContractMethod<
    [_tokenAddress: AddressLike],
    [void],
    "payable"
  >;

  gasWallet: TypedContractMethod<[], [string], "view">;

  getDickCoinCount: TypedContractMethod<[], [bigint], "view">;

  getDickCoinInfo: TypedContractMethod<
    [_tokenAddress: AddressLike],
    [
      [string, bigint, bigint, boolean, boolean] & {
        creator: string;
        totalFeesReceived: bigint;
        creatorPaid: bigint;
        stakingActive: boolean;
        active: boolean;
      }
    ],
    "view"
  >;

  isAutoStakeReady: TypedContractMethod<
    [_tokenAddress: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  pendingWithdrawals: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  protocolWallet: TypedContractMethod<[], [string], "view">;

  registerDickCoin: TypedContractMethod<
    [_tokenAddress: AddressLike, _creator: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setAutoStakeThreshold: TypedContractMethod<
    [_threshold: BigNumberish],
    [void],
    "nonpayable"
  >;

  setGasWallet: TypedContractMethod<
    [_wallet: AddressLike],
    [void],
    "nonpayable"
  >;

  setProtocolWallet: TypedContractMethod<
    [_wallet: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CREATOR_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "GAS_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_DICKCOINS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PROTOCOL_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TOTAL_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "allDickCoins"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "autoStakeThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "dickCoins"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, bigint, bigint, boolean] & {
        creator: string;
        tokenAddress: string;
        totalFeesReceived: bigint;
        creatorPaid: bigint;
        stakingDeployed: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "distributeFees"
  ): TypedContractMethod<[_tokenAddress: AddressLike], [void], "payable">;
  getFunction(
    nameOrSignature: "gasWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getDickCoinCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDickCoinInfo"
  ): TypedContractMethod<
    [_tokenAddress: AddressLike],
    [
      [string, bigint, bigint, boolean, boolean] & {
        creator: string;
        totalFeesReceived: bigint;
        creatorPaid: bigint;
        stakingActive: boolean;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isAutoStakeReady"
  ): TypedContractMethod<[_tokenAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingWithdrawals"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "protocolWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerDickCoin"
  ): TypedContractMethod<
    [_tokenAddress: AddressLike, _creator: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAutoStakeThreshold"
  ): TypedContractMethod<[_threshold: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setGasWallet"
  ): TypedContractMethod<[_wallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setProtocolWallet"
  ): TypedContractMethod<[_wallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "AutoStakeThresholdReached"
  ): TypedContractEvent<
    AutoStakeThresholdReachedEvent.InputTuple,
    AutoStakeThresholdReachedEvent.OutputTuple,
    AutoStakeThresholdReachedEvent.OutputObject
  >;
  getEvent(
    key: "CreatorPaid"
  ): TypedContractEvent<
    CreatorPaidEvent.InputTuple,
    CreatorPaidEvent.OutputTuple,
    CreatorPaidEvent.OutputObject
  >;
  getEvent(
    key: "DickCoinRegistered"
  ): TypedContractEvent<
    DickCoinRegisteredEvent.InputTuple,
    DickCoinRegisteredEvent.OutputTuple,
    DickCoinRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "FeesReceived"
  ): TypedContractEvent<
    FeesReceivedEvent.InputTuple,
    FeesReceivedEvent.OutputTuple,
    FeesReceivedEvent.OutputObject
  >;
  getEvent(
    key: "FeesSplit"
  ): TypedContractEvent<
    FeesSplitEvent.InputTuple,
    FeesSplitEvent.OutputTuple,
    FeesSplitEvent.OutputObject
  >;
  getEvent(
    key: "GasWalletUpdated"
  ): TypedContractEvent<
    GasWalletUpdatedEvent.InputTuple,
    GasWalletUpdatedEvent.OutputTuple,
    GasWalletUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferStarted"
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ProtocolWalletUpdated"
  ): TypedContractEvent<
    ProtocolWalletUpdatedEvent.InputTuple,
    ProtocolWalletUpdatedEvent.OutputTuple,
    ProtocolWalletUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawalPending"
  ): TypedContractEvent<
    WithdrawalPendingEvent.InputTuple,
    WithdrawalPendingEvent.OutputTuple,
    WithdrawalPendingEvent.OutputObject
  >;

  filters: {
    "AutoStakeThresholdReached(address,uint256)": TypedContractEvent<
      AutoStakeThresholdReachedEvent.InputTuple,
      AutoStakeThresholdReachedEvent.OutputTuple,
      AutoStakeThresholdReachedEvent.OutputObject
    >;
    AutoStakeThresholdReached: TypedContractEvent<
      AutoStakeThresholdReachedEvent.InputTuple,
      AutoStakeThresholdReachedEvent.OutputTuple,
      AutoStakeThresholdReachedEvent.OutputObject
    >;

    "CreatorPaid(address,uint256)": TypedContractEvent<
      CreatorPaidEvent.InputTuple,
      CreatorPaidEvent.OutputTuple,
      CreatorPaidEvent.OutputObject
    >;
    CreatorPaid: TypedContractEvent<
      CreatorPaidEvent.InputTuple,
      CreatorPaidEvent.OutputTuple,
      CreatorPaidEvent.OutputObject
    >;

    "DickCoinRegistered(address,address)": TypedContractEvent<
      DickCoinRegisteredEvent.InputTuple,
      DickCoinRegisteredEvent.OutputTuple,
      DickCoinRegisteredEvent.OutputObject
    >;
    DickCoinRegistered: TypedContractEvent<
      DickCoinRegisteredEvent.InputTuple,
      DickCoinRegisteredEvent.OutputTuple,
      DickCoinRegisteredEvent.OutputObject
    >;

    "FeesReceived(address,uint256)": TypedContractEvent<
      FeesReceivedEvent.InputTuple,
      FeesReceivedEvent.OutputTuple,
      FeesReceivedEvent.OutputObject
    >;
    FeesReceived: TypedContractEvent<
      FeesReceivedEvent.InputTuple,
      FeesReceivedEvent.OutputTuple,
      FeesReceivedEvent.OutputObject
    >;

    "FeesSplit(address,uint256,uint256,uint256)": TypedContractEvent<
      FeesSplitEvent.InputTuple,
      FeesSplitEvent.OutputTuple,
      FeesSplitEvent.OutputObject
    >;
    FeesSplit: TypedContractEvent<
      FeesSplitEvent.InputTuple,
      FeesSplitEvent.OutputTuple,
      FeesSplitEvent.OutputObject
    >;

    "GasWalletUpdated(address,address)": TypedContractEvent<
      GasWalletUpdatedEvent.InputTuple,
      GasWalletUpdatedEvent.OutputTuple,
      GasWalletUpdatedEvent.OutputObject
    >;
    GasWalletUpdated: TypedContractEvent<
      GasWalletUpdatedEvent.InputTuple,
      GasWalletUpdatedEvent.OutputTuple,
      GasWalletUpdatedEvent.OutputObject
    >;

    "OwnershipTransferStarted(address,address)": TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ProtocolWalletUpdated(address,address)": TypedContractEvent<
      ProtocolWalletUpdatedEvent.InputTuple,
      ProtocolWalletUpdatedEvent.OutputTuple,
      ProtocolWalletUpdatedEvent.OutputObject
    >;
    ProtocolWalletUpdated: TypedContractEvent<
      ProtocolWalletUpdatedEvent.InputTuple,
      ProtocolWalletUpdatedEvent.OutputTuple,
      ProtocolWalletUpdatedEvent.OutputObject
    >;

    "WithdrawalPending(address,uint256)": TypedContractEvent<
      WithdrawalPendingEvent.InputTuple,
      WithdrawalPendingEvent.OutputTuple,
      WithdrawalPendingEvent.OutputObject
    >;
    WithdrawalPending: TypedContractEvent<
      WithdrawalPendingEvent.InputTuple,
      WithdrawalPendingEvent.OutputTuple,
      WithdrawalPendingEvent.OutputObject
    >;
  };
}
