/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SizeRewardsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptOwnership"
      | "claimMultipleEpochs"
      | "claimRewards"
      | "currentEpoch"
      | "depositRewards"
      | "epochClaimed"
      | "epochs"
      | "finalizeEpoch"
      | "gasWallet"
      | "getClaimable"
      | "getCurrentEpochInfo"
      | "isDistributor"
      | "lastDistributionTime"
      | "minDistributionInterval"
      | "owner"
      | "pendingOwner"
      | "pendingRewardPool"
      | "protocolWallet"
      | "renounceOwnership"
      | "setDistributor"
      | "setGasWallet"
      | "setProtocolWallet"
      | "setUserWeights"
      | "sizeToken"
      | "transferOwnership"
      | "userEpochWeight"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DistributorUpdated"
      | "EpochFinalized"
      | "OwnershipTransferStarted"
      | "OwnershipTransferred"
      | "RewardsClaimed"
      | "RewardsDeposited"
      | "UserWeightSet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimMultipleEpochs",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "claimRewards",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "currentEpoch",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositRewards",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "epochClaimed",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "epochs",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeEpoch",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "gasWallet", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getClaimable",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentEpochInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isDistributor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastDistributionTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minDistributionInterval",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingRewardPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "protocolWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDistributor",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setGasWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setProtocolWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setUserWeights",
    values: [AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(functionFragment: "sizeToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userEpochWeight",
    values: [BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimMultipleEpochs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentEpoch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "epochClaimed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "epochs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "finalizeEpoch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gasWallet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getClaimable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentEpochInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastDistributionTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minDistributionInterval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingRewardPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "protocolWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGasWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProtocolWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUserWeights",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sizeToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userEpochWeight",
    data: BytesLike
  ): Result;
}

export namespace DistributorUpdatedEvent {
  export type InputTuple = [distributor: AddressLike, status: boolean];
  export type OutputTuple = [distributor: string, status: boolean];
  export interface OutputObject {
    distributor: string;
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EpochFinalizedEvent {
  export type InputTuple = [
    epoch: BigNumberish,
    totalPool: BigNumberish,
    totalWeight: BigNumberish
  ];
  export type OutputTuple = [
    epoch: bigint,
    totalPool: bigint,
    totalWeight: bigint
  ];
  export interface OutputObject {
    epoch: bigint;
    totalPool: bigint;
    totalWeight: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardsClaimedEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    epoch: BigNumberish
  ];
  export type OutputTuple = [user: string, amount: bigint, epoch: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
    epoch: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardsDepositedEvent {
  export type InputTuple = [amount: BigNumberish, epoch: BigNumberish];
  export type OutputTuple = [amount: bigint, epoch: bigint];
  export interface OutputObject {
    amount: bigint;
    epoch: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserWeightSetEvent {
  export type InputTuple = [
    epoch: BigNumberish,
    user: AddressLike,
    weight: BigNumberish
  ];
  export type OutputTuple = [epoch: bigint, user: string, weight: bigint];
  export interface OutputObject {
    epoch: bigint;
    user: string;
    weight: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SizeRewards extends BaseContract {
  connect(runner?: ContractRunner | null): SizeRewards;
  waitForDeployment(): Promise<this>;

  interface: SizeRewardsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  claimMultipleEpochs: TypedContractMethod<
    [_epochs: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  claimRewards: TypedContractMethod<
    [_epoch: BigNumberish],
    [void],
    "nonpayable"
  >;

  currentEpoch: TypedContractMethod<[], [bigint], "view">;

  depositRewards: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  epochClaimed: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  epochs: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, boolean] & {
        totalPool: bigint;
        totalWeight: bigint;
        timestamp: bigint;
        finalized: boolean;
      }
    ],
    "view"
  >;

  finalizeEpoch: TypedContractMethod<
    [_totalWeight: BigNumberish],
    [void],
    "nonpayable"
  >;

  gasWallet: TypedContractMethod<[], [string], "view">;

  getClaimable: TypedContractMethod<
    [_user: AddressLike, _epoch: BigNumberish],
    [bigint],
    "view"
  >;

  getCurrentEpochInfo: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        epoch: bigint;
        pool: bigint;
        lastDist: bigint;
        nextDist: bigint;
      }
    ],
    "view"
  >;

  isDistributor: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  lastDistributionTime: TypedContractMethod<[], [bigint], "view">;

  minDistributionInterval: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  pendingRewardPool: TypedContractMethod<[], [bigint], "view">;

  protocolWallet: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setDistributor: TypedContractMethod<
    [_addr: AddressLike, _status: boolean],
    [void],
    "nonpayable"
  >;

  setGasWallet: TypedContractMethod<
    [_wallet: AddressLike],
    [void],
    "nonpayable"
  >;

  setProtocolWallet: TypedContractMethod<
    [_wallet: AddressLike],
    [void],
    "nonpayable"
  >;

  setUserWeights: TypedContractMethod<
    [_users: AddressLike[], _weights: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  sizeToken: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  userEpochWeight: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimMultipleEpochs"
  ): TypedContractMethod<[_epochs: BigNumberish[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimRewards"
  ): TypedContractMethod<[_epoch: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "currentEpoch"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "depositRewards"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "epochClaimed"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "epochs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, boolean] & {
        totalPool: bigint;
        totalWeight: bigint;
        timestamp: bigint;
        finalized: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "finalizeEpoch"
  ): TypedContractMethod<[_totalWeight: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "gasWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getClaimable"
  ): TypedContractMethod<
    [_user: AddressLike, _epoch: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCurrentEpochInfo"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        epoch: bigint;
        pool: bigint;
        lastDist: bigint;
        nextDist: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isDistributor"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastDistributionTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minDistributionInterval"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingRewardPool"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "protocolWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDistributor"
  ): TypedContractMethod<
    [_addr: AddressLike, _status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setGasWallet"
  ): TypedContractMethod<[_wallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setProtocolWallet"
  ): TypedContractMethod<[_wallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setUserWeights"
  ): TypedContractMethod<
    [_users: AddressLike[], _weights: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sizeToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userEpochWeight"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  getEvent(
    key: "DistributorUpdated"
  ): TypedContractEvent<
    DistributorUpdatedEvent.InputTuple,
    DistributorUpdatedEvent.OutputTuple,
    DistributorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "EpochFinalized"
  ): TypedContractEvent<
    EpochFinalizedEvent.InputTuple,
    EpochFinalizedEvent.OutputTuple,
    EpochFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferStarted"
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RewardsClaimed"
  ): TypedContractEvent<
    RewardsClaimedEvent.InputTuple,
    RewardsClaimedEvent.OutputTuple,
    RewardsClaimedEvent.OutputObject
  >;
  getEvent(
    key: "RewardsDeposited"
  ): TypedContractEvent<
    RewardsDepositedEvent.InputTuple,
    RewardsDepositedEvent.OutputTuple,
    RewardsDepositedEvent.OutputObject
  >;
  getEvent(
    key: "UserWeightSet"
  ): TypedContractEvent<
    UserWeightSetEvent.InputTuple,
    UserWeightSetEvent.OutputTuple,
    UserWeightSetEvent.OutputObject
  >;

  filters: {
    "DistributorUpdated(address,bool)": TypedContractEvent<
      DistributorUpdatedEvent.InputTuple,
      DistributorUpdatedEvent.OutputTuple,
      DistributorUpdatedEvent.OutputObject
    >;
    DistributorUpdated: TypedContractEvent<
      DistributorUpdatedEvent.InputTuple,
      DistributorUpdatedEvent.OutputTuple,
      DistributorUpdatedEvent.OutputObject
    >;

    "EpochFinalized(uint256,uint256,uint256)": TypedContractEvent<
      EpochFinalizedEvent.InputTuple,
      EpochFinalizedEvent.OutputTuple,
      EpochFinalizedEvent.OutputObject
    >;
    EpochFinalized: TypedContractEvent<
      EpochFinalizedEvent.InputTuple,
      EpochFinalizedEvent.OutputTuple,
      EpochFinalizedEvent.OutputObject
    >;

    "OwnershipTransferStarted(address,address)": TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RewardsClaimed(address,uint256,uint256)": TypedContractEvent<
      RewardsClaimedEvent.InputTuple,
      RewardsClaimedEvent.OutputTuple,
      RewardsClaimedEvent.OutputObject
    >;
    RewardsClaimed: TypedContractEvent<
      RewardsClaimedEvent.InputTuple,
      RewardsClaimedEvent.OutputTuple,
      RewardsClaimedEvent.OutputObject
    >;

    "RewardsDeposited(uint256,uint256)": TypedContractEvent<
      RewardsDepositedEvent.InputTuple,
      RewardsDepositedEvent.OutputTuple,
      RewardsDepositedEvent.OutputObject
    >;
    RewardsDeposited: TypedContractEvent<
      RewardsDepositedEvent.InputTuple,
      RewardsDepositedEvent.OutputTuple,
      RewardsDepositedEvent.OutputObject
    >;

    "UserWeightSet(uint256,address,uint256)": TypedContractEvent<
      UserWeightSetEvent.InputTuple,
      UserWeightSetEvent.OutputTuple,
      UserWeightSetEvent.OutputObject
    >;
    UserWeightSet: TypedContractEvent<
      UserWeightSetEvent.InputTuple,
      UserWeightSetEvent.OutputTuple,
      UserWeightSetEvent.OutputObject
    >;
  };
}
